GET http://localhost:7070/tag/list?projectId=1
Content-Type: application/json

###
GET http://localhost:7070/tag/list?taskId=1
Content-Type: application/json

###
POST http://localhost:7070/tag/register
Content-Type: application/json

{
  "projectId": 1,
  "name": "test"
}

###
PUT http://localhost:7070/tag/24/modify
Content-Type: application/json

{
  "name": "modify"
}

###
DELETE http://localhost:7070/tag/1/delete